language: python
before_script:
  - echo $GCLOUD_SERVICE_KEY | base64 --decode > service_account.json
  - cat service_account.json | docker login -u _json_key --password-stdin https://gcr.io
jobs:
  include:
    - stage: test
      script:
        - docker pull gcr.io/battlesnake-io/play:latest
        - docker build -t gcr.io/battlesnake-io/play:$TRAVIS_PULL_REQUEST_SHA -t gcr.io/battlesnake-io/play:latest --cache-from gcr.io/battlesnake-io/play:latest
        - docker run -e ENV=local gcr.io/battlesnake-io/play:$TRAVIS_PULL_REQUEST_SHA pytest
        - docker run dlsteuer/black --check .
        - docker run alpine/flake8 .
        - docker push gcr.io/battlesnake-io/play:latest