# Generated by Django 2.0.10 on 2019-02-10 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("leaderboard", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="gameleaderboard",
            name="ranked",
            field=models.BooleanField(default=False),
        )
    ]
