# Generated by Django 2.0.10 on 2019-02-14 07:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0002_snake_healthy")]

    operations = [
        migrations.AddField(
            model_name="gamesnake",
            name="name",
            field=models.CharField(default="", max_length=128),
        ),
        migrations.AlterField(
            model_name="profile",
            name="optin_marketing",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="snake",
            name="name",
            field=models.CharField(
                max_length=128,
                validators=[django.core.validators.MinLengthValidator(3)],
            ),
        ),
    ]
