# Generated by Django 2.0.10 on 2019-02-14 22:54

from django.db import migrations, models
import django.db.models.deletion


def migrate_profile(apps, schema_editor):
    Snake = apps.get_model("core", "Snake")
    Profile = apps.get_model("core", "Profile")
    snakes = Snake.objects.all()
    for snake in snakes:
        try:
            snake.profile = snake.user.profile
        except Profile.DoesNotExist:
            profile = Profile.objects.create(user=snake.user)
            snake.profile = profile
        snake.save()


class Migration(migrations.Migration):

    dependencies = [("core", "0003_auto_20190214_0745")]

    operations = [
        migrations.AddField(
            model_name="snake",
            name="profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.Profile",
            ),
        ),
        migrations.RunPython(migrate_profile),
    ]
