# Generated by Django 2.0.10 on 2019-02-15 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("core", "0004_snake_profile")]

    operations = [
        migrations.RemoveField(model_name="snake", name="user"),
        migrations.AlterField(
            model_name="snake",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.Profile"
            ),
        ),
    ]
