# Generated by Django 2.0.10 on 2019-02-23 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0006_auto_20190219_0607")]

    operations = [
        migrations.AddField(
            model_name="game",
            name="engine_url",
            field=models.CharField(max_length=128, null=True),
        )
    ]
