# Generated by Django 2.0.10 on 2019-02-11 18:16

from django.db import migrations


def update_previous_admins(apps, schema_editor):
    User = apps.get_model("authentication", "User")
    admins = [
        "brandonb927",
        "bvanvugt",
        "codeallthethingz",
        "coldog",
        "dlsteuer",
        "joram",
        "matthieudolci",
        "tristan-swu",
    ]
    users = User.objects.filter(username__in=admins)
    for u in users:
        u.is_superuser = True


class Migration(migrations.Migration):

    dependencies = [("authentication", "0001_initial")]

    operations = [migrations.RunPython(update_previous_admins)]
