# Generated by Django 2.0.10 on 2019-02-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("authentication", "0002_auto_20190211_1816")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_commentator",
            field=models.BooleanField(default=False),
        )
    ]
