# Generated by Django 2.0.10 on 2019-02-10 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import util.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Heat",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(default=1)),
                ("desired_games", models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name="HeatGame",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UW", "Not Casted Yet"),
                            ("W", "Casting"),
                            ("WD", "Casted"),
                        ],
                        default="UW",
                        max_length=2,
                    ),
                ),
                ("number", models.IntegerField(default=1)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="core.Game"
                    ),
                ),
                (
                    "heat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournament.Heat",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Round",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="SnakeHeat",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "heat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournament.Heat",
                    ),
                ),
                (
                    "snake",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.Snake"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    util.fields.ShortUUIDField(
                        max_length=128, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField()),
                ("can_register_in_tournaments", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournament.Team",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_member",
                        to=settings.AUTH_USER_MODEL,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("casting_uri", models.CharField(default="", max_length=1024)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("LO", "Locked"),
                            ("HI", "Hidden"),
                            ("RE", "Registration"),
                            ("PR", "In Progress"),
                            ("JR", "Complete"),
                        ],
                        default="LO",
                        max_length=2,
                    ),
                ),
                ("single_snake_per_team", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=256)),
                ("date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="TournamentBracket",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("board_width", models.IntegerField(default=11)),
                ("board_height", models.IntegerField(default=11)),
                ("board_food", models.IntegerField(default=2)),
                (
                    "board_max_turns_to_next_food_spawn",
                    models.IntegerField(blank=True, default=15, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TournamentSnake",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bracket",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tournament.TournamentBracket",
                    ),
                ),
                (
                    "snake",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.Snake"
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournament.Tournament",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="tournamentbracket",
            name="snakes",
            field=models.ManyToManyField(
                through="tournament.TournamentSnake", to="core.Snake"
            ),
        ),
        migrations.AddField(
            model_name="tournamentbracket",
            name="tournament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tournament.Tournament"
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="snakes",
            field=models.ManyToManyField(
                through="tournament.TournamentSnake", to="core.Snake"
            ),
        ),
        migrations.AddField(
            model_name="round",
            name="tournament_bracket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tournament.TournamentBracket",
            ),
        ),
        migrations.AddField(
            model_name="heat",
            name="round",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tournament.Round"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="teammember", unique_together={("team", "user")}
        ),
        migrations.AlterUniqueTogether(
            name="snakeheat", unique_together={("heat", "snake")}
        ),
        migrations.AlterUniqueTogether(
            name="round", unique_together={("number", "tournament_bracket")}
        ),
    ]
