# Generated by Django 2.0.10 on 2019-02-14 19:32

from django.db import migrations
import util.fields


class Migration(migrations.Migration):

    dependencies = [("tournament", "0003_tournamentsnake_team")]

    operations = [
        migrations.AlterField(
            model_name="heat",
            name="id",
            field=util.fields.ShortUUIDField(
                max_length=128, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="heatgame",
            name="id",
            field=util.fields.ShortUUIDField(
                max_length=128, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="round",
            name="id",
            field=util.fields.ShortUUIDField(
                max_length=128, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="id",
            field=util.fields.ShortUUIDField(
                max_length=128, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="tournamentbracket",
            name="id",
            field=util.fields.ShortUUIDField(
                max_length=128, primary_key=True, serialize=False
            ),
        ),
    ]
