# Generated by Django 2.0.10 on 2019-02-15 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_snake_profile"),
        ("tournament", "0004_auto_20190214_1932"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="teammember", unique_together=set()),
        migrations.RemoveField(model_name="teammember", name="team"),
        migrations.RemoveField(model_name="teammember", name="user"),
        migrations.AddField(
            model_name="team",
            name="team_members",
            field=models.ManyToManyField(to="core.Profile"),
        ),
        migrations.DeleteModel(name="TeamMember"),
    ]
